// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSewcBkrthet16PaOWi48kZ0lztZWh6jY',
    appId: '1:743873038855:web:f127e7055c74288aba38a2',
    messagingSenderId: '743873038855',
    projectId: 'phone-firebase-c2c88',
    authDomain: 'phone-firebase-c2c88.firebaseapp.com',
    storageBucket: 'phone-firebase-c2c88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4FqehAdaYbLI1WrkhcVhsQ_Edg68bS8',
    appId: '1:743873038855:android:572696bcb3537460ba38a2',
    messagingSenderId: '743873038855',
    projectId: 'phone-firebase-c2c88',
    storageBucket: 'phone-firebase-c2c88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXCJKa3Slwsd9xPo8zuQkaswGFrPT0MtQ',
    appId: '1:743873038855:ios:7e64d225eb8acd25ba38a2',
    messagingSenderId: '743873038855',
    projectId: 'phone-firebase-c2c88',
    storageBucket: 'phone-firebase-c2c88.appspot.com',
    androidClientId: '743873038855-r216ha6uog6g2uh1rjk1oq5g9abomao9.apps.googleusercontent.com',
    iosClientId: '743873038855-eopbsm4rjaca8ddr1q8ggcemagbjtsqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXCJKa3Slwsd9xPo8zuQkaswGFrPT0MtQ',
    appId: '1:743873038855:ios:7e64d225eb8acd25ba38a2',
    messagingSenderId: '743873038855',
    projectId: 'phone-firebase-c2c88',
    storageBucket: 'phone-firebase-c2c88.appspot.com',
    androidClientId: '743873038855-r216ha6uog6g2uh1rjk1oq5g9abomao9.apps.googleusercontent.com',
    iosClientId: '743873038855-eopbsm4rjaca8ddr1q8ggcemagbjtsqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
